FROM golang:1.22-alpine

# 작업 디렉토리 설정
WORKDIR /server

# air 설치 (실시간 리로드 도구)
RUN go install github.com/air-verse/air@latest

# 의존성 파일 복사 및 다운로드
COPY go.mod go.sum ./
RUN go mod download

# 소스 코드 복사
COPY . .

# air를 사용하여 애플리케이션 실행
CMD ["air", "-c", ".air.toml"]