version: "3.8"
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
  server:
    build:
      context: ./server
      dockerfile: ../Dockerfile.server
    environment:
      - APP_ENV=development
      - PORT=3333
    ports:
      - "3333:3333"
    volumes:
      - ./server:/server
    depends_on:
      - db
  client:
    build:
      context: ./client
      dockerfile: ../Dockerfile.client
    environment:
      - APP_ENV=development
    ports:
      - "3010:3010"
    volumes:
      - ./client:/client
    depends_on:
      - server